version: '3.3'
services:
  mysql:
    image: mysql:5.7
    container_name: crud-app-mysql
    volumes:
       - ./crud-app.sql:/docker-entrypoint-initdb.d/crud-app.sql
       - ./data:/var/lib/mysql
    environment:
        MYSQL_DATABASE: crud_app
        MYSQL_ROOT_PASSWORD: crud-app
    ports:
      - "3306:3306"
  crud-app:
      depends_on:
        - mysql
      build: .
      links:
        - mysql
      container_name: crud-app
      ports:
        - "5000:5000"
      restart: always
      volumes:
        - ./:/crud-app
      environment:
        MYSQL_HOST: mysql
        MYSQL_USER: root
        MYSQL_PASSWORD: crud-app
        MYSQL_DB: crud_app